version: "3.2"
services:
  user-service:
    image: user-service
    ports:
      - "8081:8081"
      
  user-client:
    image: user-client
    ports:
      - "8080:8080"

  # portainer:
  #   image: portainer/portainer
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer:/data
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]

volumes:
  portainer: